//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DovizKurlari2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doviz
    {
        public int DovizId { get; set; }
        public string Isim { get; set; }
        public string Kod { get; set; }
        public string AlisKur { get; set; }
        public string SatisKur { get; set; }
        public string Tarih { get; set; }
    }
}
